apiVersion: v1
kind: Service
metadata:
  name: slytherin-svc
spec:
  selector:
    app: python-with-prometheus
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: app
    - protocol: TCP
      port: 8090
      targetPort: 8090
      name: metrics